### ISSUE TITLE
Iphone 6 and 6 plus bug

### ISSUE THREAD

**Issue by rajat93** [romaonthego/REFrostedViewController#116]
I am having an issue with REFrostedViewController when i run my app in iphone 6 and 6 plus. When i show side panel using REFrostedViewController, the side panel shows strange behaviour. It seems like the frame changes suddenly and comes back to same position very fast which looks like height is bigger first and then changes back to desired positon. 

The bug can be seen in the side panel of the following app, but only in Iphone 6 and 6 plus. Works fine on other iphones.

https://itunes.apple.com/us/app/instamigos/id931926219?mt=8

Please help.

**Comment by marclluz** [comment]
Did you manage to fix this?

**Comment by rajat93** [comment]
Yes, it is a rather simple bug. You just have to add this line in your
AppDelegate.

    frostedViewCtlr.liveBlur = YES;


Let me know if this works out for you or if it doesn't.

Best Wishes.

**Comment by marclluz** [comment]
I solved it enabling the live blur but my blur tint disappeared...

**Comment by rajat93** [comment]
You can give the blur color too.
I think there is some function called "liveblurstyle".

**Comment by marclluz** [comment]
I just can set it to Light or Dark not custom blur color

**Comment by rajat93** [comment]
That you'll have to figure out by yourself.
Sorry
