### ISSUE TITLE
Rotation issues in general & landscape appearance

### ISSUE THREAD

**Issue by SpicaThor** [romaonthego/REFrostedViewController#21]
Hi.
There is an issue with landscape mode, where the menu controller's frame isn't either calculated or set properly causing what you can see in attached gif. 
![refrost](https://f.cloud.github.com/assets/768096/1367890/1297a728-3968-11e3-8532-b15d9434f5d6.gif)
As you can see a menu view controller gets frame as if it was portrait and so the scrolling is continue under visible part of the screen...

**Comment by zfdang** [comment]
any explanation about this issue?

**Comment by Krusheuski** [comment]
The problem is reproduced in the latest version!
