### ISSUE TITLE
Menu dragging with content

### ISSUE THREAD

**Issue by bizibizi** [romaonthego/REFrostedViewController#67]
For example I have left REFrostedViewController.
With standard parameters.
If I drag menu to the right - it resize yourself but not content.
If it possible to disable this gestures without disable anything else or enable resize content? I prefer second way :)

**Comment by Ananthakrishna-toorq** [comment]
Hi, and thanks for this awesome content. :)
I wanted to resize the dragMenu according to the screen orientation, I tried     
CGFloat screenHeight =[UIScreen mainScreen].bounds.size.height/4;
CGFloat screenWidth =[UIScreen mainScreen].bounds.size.width;
 self.limitMenuViewSize=YES;
 [self resizeMenuViewControllerToSize:CGSizeMake(screenWidth, screenHeight)];

in didViewRotate method in rootview controller. but It's not happening. Is there anything I am missing here?
